// build_obsidian_fx_plugin.js — bundle the Obsidian fx preview plugin into
// the vault. Run with: bun run obsidian:fx:build
//
// Output: <vault>/.obsidian/plugins/solarisael-fx/{main.js,styles.css,manifest.json}
// main.js bundles the plugin shell + the site's own fx parser and hydration
// runtime (CJS, `obsidian` external). styles.css is the vendor fx CSS with a
// fallback block for the site custom properties Obsidian does not define.

import { mkdir } from "node:fs/promises";
import path from "node:path";

import { OBSIDIAN_VAULT_ROOT } from "../src/config/obsidian_vault_root.js";

const repo_root = path.resolve(import.meta.dir, "..");
const plugin_source_dir = path.join(repo_root, "obsidian", "fx_preview_plugin");
const vendor_css_dir = path.join(repo_root, "public", "vendor", "fx", "css");
const output_dir = path.join(
  OBSIDIAN_VAULT_ROOT,
  ".obsidian",
  "plugins",
  "solarisael-fx",
);

// enough: fallback values are copied from src/styles/tokens.css + index.css;
// re-copy when the site palette moves. Parsing the CSS at build time is the
// way up if drift ever bites.
const site_var_fallbacks = `/* generated by scripts/build_obsidian_fx_plugin.js — edit the source, not this file */
body {
  --site_style_accent: oklch(73.5% 0.075 80);
  --site_style_accent_alt: oklch(80% 0.07 80);
  --color-albedo: oklch(88% 0.025 247.839);
  --color-nigredo: oklch(55.1% 0.027 264.364);
  --color-citrinitas: oklch(76% 0.12 58deg);
  --color-rubedo: oklch(64% 0.19 26deg);
  --color-codex: oklch(66% 0.06 290);
  --site_border_width_hairline: 0.5px;
}

.sol__fx_marker_hidden {
  display: none;
}
`;

const vendor_css_names = ["text.css", "overlay.css", "combat.css"];

const build = async () => {
  await mkdir(output_dir, { recursive: true });

  const bundle = await Bun.build({
    entrypoints: [path.join(plugin_source_dir, "main.js")],
    external: ["obsidian"],
    format: "cjs",
    target: "browser",
  });

  if (!bundle.success) {
    for (const log of bundle.logs) {
      console.error(String(log));
    }
    process.exit(1);
  }

  await Bun.write(
    path.join(output_dir, "main.js"),
    await bundle.outputs[0].text(),
  );

  const css_parts = [site_var_fallbacks];

  for (const css_name of vendor_css_names) {
    css_parts.push(`/* ${css_name} — vendored from public/vendor/fx/css */`);
    css_parts.push(
      await Bun.file(path.join(vendor_css_dir, css_name)).text(),
    );
  }

  await Bun.write(path.join(output_dir, "styles.css"), css_parts.join("\n\n"));
  await Bun.write(
    path.join(output_dir, "manifest.json"),
    await Bun.file(path.join(plugin_source_dir, "manifest.json")).text(),
  );

  console.log(`solarisael-fx built into ${output_dir}`);
};

await build();
